### ISSUE TITLE
[feature-request]: Create Material Design-based theme for all the websites?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-theme#15]
### What feature would you like to request?

Since we're using Material Design for the products, might be good to have a consistent theme across all styling. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by signekb** [comment]
@lwjohnst86 Would you mind elaborating on this?

**Comment by lwjohnst86** [comment]
This is less to do with the general theming/colour scheme/fonts/CSS, and more to do with how websites are laid out. See https://m3.material.io/foundations

While Quarto themes cover a lot of the concepts within Material, things we add to it can't get covered. For instance, accessibility: https://m3.material.io/foundations/overview/assistive-technology. Or choice of words: https://m3.material.io/foundations/content-design/global-writing/word-choice

It also does include some CSS things, like our buttons on the landing page https://seedcase-project.org/ don't follow our styles in Sprout.

**Comment by signekb** [comment]
Ah, thanks! What should the output of this task be? A post? Something in Figma?

**Comment by lwjohnst86** [comment]
@signekb it would likely be a combination of CSS styling and a guide/contributing post (in community) on how we write and display content. Think of it like a naming scheme, but a scheme for laying out content, writing content, and using images etc.

**Comment by signekb** [comment]
@lwjohnst86 Ah, okay. So CSS in the `seedcase-theme` repo and a post in `community`?

**Comment by lwjohnst86** [comment]
Yea, I think that's a good starting point 🌛🌝

**Comment by signekb** [comment]
I'll give it a go tomorrow 🫡
