### ISSUE TITLE
Expand on logo to include title (Seedcase Project)

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-theme#22]

**Comment by signekb** [comment]
@seedcase-project/developers I have done brainstorm on this which you can find on Figma [here](https://www.figma.com/design/czeKwMxVLKPNQDX42eiTxq/Wireframes?node-id=1468-3716&t=WlboGK9My7m1YYMa-0). 

Please comment your feedback in there (by making comments by the logo/frame) and report back here which one(s) you like. I have numbered them to make them easier to refer to. 

If you have any ideas, feel free to add them yourself (in new frames in. Figma) or write them down, so I can visualise them :)

**Comment by K-Beicher** [comment]
I'd be happy to work with all of them except 2.1, light theme with white background. The light green on white makes it far to bright for my taste.

**Comment by signekb** [comment]
Agreed! I'll remove it.
